'use client';

import {FlowArrow, NavArrow} from '@/components/directional-arrow';
import {useCallback, useEffect, useMemo, useState} from 'react';
import {useLocale, useTranslations} from 'next-intl';
import type {AppLocale} from '@/i18n/config';
import {lifeCoachApi} from '@/lib/life-coach/api-client';
import {loadUserPreferences} from '@/lib/user-preferences';
import {computeStreak} from '@/lib/life-coach/streak-utils';
import type {AiCoachingInsight, DailyBabyStep, Goal, LifeDomainState, Milestone} from '@/lib/life-coach/types';
import {DailyBabyStepsList} from '../daily-baby-steps-list';
import {LifeCoachAuthShell} from '../life-coach-auth-shell';
import {ProgressDashboard} from '../shared/progress-dashboard';
import {GoalEditCard} from '../shared/goal-edit-card';
import {DomainGoalTabContent} from '../shared/domain-goal-tab-content';
import {useAutoGenerateDomainSteps} from '../shared/use-auto-generate-domain-steps';
import {generateDomainDailySteps} from '@/lib/life-coach/generate-domain-daily-steps';
import {SurvivalModeBanner} from '@/components/life-coach/survival-mode-banner';
import {fetchFormulationCoachContext} from '@/lib/formulation/personalized-challenge-storage';
import type {ComebackMessaging} from '@/lib/formulation/comeback-messaging';
import {isSoftSurvivalMode, type LoadAdaptationContext} from '@/lib/formulation/load-adaptation-routing';
import {useToast} from '@/components/feedback/toast-provider';
import {LoadingErrorPanel} from '@/components/feedback/loading-error-panel';
import {MobileQuickAction} from '@/components/feedback/mobile-quick-action';
import {AiGeneratingProgress} from '../shared/ai-generating-progress';
import {NextActionBar} from '@/components/feedback/next-action-bar';
import {todayYMD} from '@/lib/date-utils';
import {DomainDetailTabNav, type DomainDetailTab} from '../shared/domain-detail-tabs';
import {DomainDetailCompactHeader} from '../shared/domain-detail-compact-header';
import {DomainInsightsTabContent} from '../shared/domain-insights-tab-content';
import {HealthCurrentPhase} from './health-current-phase';
import {HealthGoalWizard} from './health-goal-wizard';
import {DailyFocusCard} from '../shared/daily-focus-card';
import type {DailyFocusContext} from '@/lib/daily-focus-context';

type GoalWithMilestones = Goal & {milestones?: Milestone[]};

export function HealthDomainDetailPage() {
  return (
    <main className="section-block border-t-0">
      <div className="page-shell">
        <LifeCoachAuthShell>{() => <HealthDetailContent />}</LifeCoachAuthShell>
      </div>
    </main>
  );
}

function HealthDetailContent() {
  const t = useTranslations();
  const locale = useLocale() as AppLocale;
  const [loading, setLoading] = useState(true);
  const [state, setState] = useState<LifeDomainState | null>(null);
  const [goals, setGoals] = useState<GoalWithMilestones[]>([]);
  const [todaySteps, setTodaySteps] = useState<DailyBabyStep[]>([]);
  const [allRecentSteps, setAllRecentSteps] = useState<DailyBabyStep[]>([]);
  const [insights, setInsights] = useState<AiCoachingInsight[]>([]);
  const [weeklyReview, setWeeklyReview] = useState<AiCoachingInsight | null>(null);
  const [dailyFocus, setDailyFocus] = useState<DailyFocusContext | null>(null);
  const [generatingSteps, setGeneratingSteps] = useState(false);
  const [creatingMissionStep, setCreatingMissionStep] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [comebackMessaging, setComebackMessaging] = useState<ComebackMessaging | null>(null);
  const [loadAdaptation, setLoadAdaptation] = useState<LoadAdaptationContext | null>(null);
  const [activeTab, setActiveTab] = useState<DomainDetailTab>('today');
  const [tabInitialized, setTabInitialized] = useState(false);
  const toast = useToast();

  const refresh = useCallback(async () => {
    setLoading(true);
    setLoadError(null);
    try {
      const result = await lifeCoachApi.getDomain('health');
      setState(result.state);
      setGoals(result.goals);
      setTodaySteps(result.todaySteps);
      setAllRecentSteps(result.recentSteps.length > 0 ? result.recentSteps : result.todaySteps);
      setInsights(result.insights);
      setWeeklyReview(result.weeklyReview);
      setDailyFocus(result.dailyFocus);
    } catch {
      setLoadError(t('lifeCoach.loadError'));
    }
    setLoading(false);
  }, [t]);

  useEffect(() => {
    const timeout = window.setTimeout(() => void refresh(), 0);
    return () => window.clearTimeout(timeout);
  }, [refresh]);

  useEffect(() => {
    void fetchFormulationCoachContext()
      .then((ctx) => {
        setComebackMessaging(ctx.comeback_messaging);
        setLoadAdaptation(ctx.load_adaptation);
      })
      .catch(() => {
        setComebackMessaging(null);
        setLoadAdaptation(null);
      });
  }, []);

  const healthSteps = todaySteps.filter((step) => step.domain === 'health');
  const pendingStep = healthSteps.find((step) => step.status === 'pending') ?? null;
  const hasHealthGoals = goals.some((goal) => goal.domain === 'health' && goal.status === 'active');
  const streak = useMemo(() => computeStreak(allRecentSteps, 'health'), [allRecentSteps]);
  const completedToday = healthSteps.filter((s) => s.status === 'completed' || s.status === 'partial').length;

  useEffect(() => {
    if (!loading && !tabInitialized) {
      const timeout = window.setTimeout(() => {
        setActiveTab(hasHealthGoals ? 'today' : 'goal');
        setTabInitialized(true);
      }, 0);
      return () => window.clearTimeout(timeout);
    }
  }, [loading, hasHealthGoals, tabInitialized]);

  useAutoGenerateDomainSteps({
    enabled: !loading && !loadError,
    locale,
    hasActiveGoal: hasHealthGoals,
    domainStepCount: healthSteps.length,
    onStart: () => setGeneratingSteps(true),
    onEnd: () => setGeneratingSteps(false),
    onDone: refresh,
  });

  async function handleGenerateSteps() {
    setGeneratingSteps(true);
    try {
      await generateDomainDailySteps(locale, healthSteps.length > 0);
      await refresh();
      toast.success(t('lifeCoach.stepsGenerated'));
      setActiveTab('today');
    } catch {
      toast.error(t('feedback.failed'));
    } finally {
      setGeneratingSteps(false);
    }
  }

  const generateLabel =
    healthSteps.length > 0 ? t('lifeCoach.regenerateTodaySteps') : t('lifeCoach.generateTodaySteps');
  const quickActionLabel = pendingStep ? t('lifeCoach.markCompleted') : generateLabel;

  async function handleQuickAction() {
    if (pendingStep) {
      try {
        await lifeCoachApi.updateDailyStepStatus(pendingStep.id, {status: 'completed'});
        await refresh();
        toast.success(t('feedback.completed'));
      } catch {
        toast.error(t('feedback.failed'));
      }
      return;
    }
    await handleGenerateSteps();
  }

  async function handleCreateMissionStep() {
    const suggested = dailyFocus?.suggestedAction;
    if (!suggested || suggested.domainId !== 'health') return;

    setCreatingMissionStep(true);
    try {
      await lifeCoachApi.createDailyStep({
        goal_id: null,
        domain: 'health',
        title: suggested.title,
        description: suggested.description,
        estimated_minutes: suggested.estimatedMinutes,
        difficulty: 'easy',
        scheduled_date: todayYMD(),
        status: 'pending',
      });
      await refresh();
      toast.success(t('feedback.saved'));
    } catch {
      toast.error(t('feedback.failed'));
    } finally {
      setCreatingMissionStep(false);
    }
  }

  return (
    <div className="grid gap-5 pb-24 sm:pb-6">
      <DomainDetailCompactHeader
        domain="health"
        streakDays={streak.current_streak}
        completedToday={completedToday}
        totalToday={healthSteps.length}
      />

      <DomainDetailTabNav
        value={activeTab}
        onChange={setActiveTab}
        goalSetupNeeded={!hasHealthGoals}
      />

      <LoadingErrorPanel
        loading={loading}
        error={loadError}
        onRetry={() => void refresh()}
        className="panel-surface p-6"
      />

      {!loading && !loadError && (
        <>
          {activeTab === 'today' && (
            <div className="grid gap-5">
              {!hasHealthGoals && (
                <div className="rounded-2xl border border-[var(--blue)]/20 bg-[var(--blue)]/[0.05] px-4 py-4">
                  <p className="text-sm leading-7 txt-soft">{t('lifeCoach.domainTabs.noGoalHint')}</p>
                  <button
                    type="button"
                    className="focus-ring mt-3 text-sm font-semibold text-[var(--blue)]"
                    onClick={() => setActiveTab('goal')}
                  >
                    {t('lifeCoach.domainTabs.goToGoal')} <NavArrow />
                  </button>
                </div>
              )}

              <SurvivalModeBanner
                pendingSteps={healthSteps.filter((s) => s.status === 'pending')}
                lifeContexts={loadUserPreferences().life_context_statuses}
                softCopy={isSoftSurvivalMode(loadAdaptation)}
                doneMessages={
                  comebackMessaging
                    ? {
                        easy: comebackMessaging.survival_done_easy,
                        skip: comebackMessaging.survival_done_skip,
                        pause: comebackMessaging.survival_done_pause,
                      }
                    : undefined
                }
                onEasyStep={async (stepId) => {
                  const pending = healthSteps.filter((s) => s.status === 'pending');
                  await Promise.all(
                    pending
                      .filter((s) => s.id !== stepId)
                      .map((s) =>
                        lifeCoachApi.updateDailyStepStatus(s.id, {
                          status: 'skipped',
                          blocker_reason: 'low_energy',
                        })
                      )
                  );
                  await refresh();
                }}
                onSkipAll={async (blocker) => {
                  const pending = healthSteps.filter((s) => s.status === 'pending');
                  await Promise.all(
                    pending.map((s) =>
                      lifeCoachApi.updateDailyStepStatus(s.id, {
                        status: 'skipped',
                        blocker_reason: blocker,
                      })
                    )
                  );
                  await lifeCoachApi.saveReflection({
                    date: todayYMD(),
                    mood_score: null,
                    energy_score: null,
                    reflection_text: '',
                    blocker_reason: blocker,
                  });
                  await refresh();
                }}
                onPauseDay={async () => {
                  const pending = healthSteps.filter((s) => s.status === 'pending');
                  await Promise.all(
                    pending.map((s) =>
                      lifeCoachApi.updateDailyStepStatus(s.id, {
                        status: 'skipped',
                        blocker_reason: 'low_energy',
                      })
                    )
                  );
                  await refresh();
                }}
              />

              {generatingSteps && <AiGeneratingProgress variant="dailySteps" />}

              <DailyFocusCard
                focus={dailyFocus}
                domain="health"
                creating={creatingMissionStep}
                onCreateMissionStep={() => void handleCreateMissionStep()}
              />

              <section
                id="health-today-plan"
                className="panel-surface scroll-mt-24 p-5 sm:p-6"
                aria-label={t('lifeCoach.todayPlan')}
              >
                <h2 className="text-lg font-bold txt-strong">{t('lifeCoach.todayPlan')}</h2>
                <div className="mt-5">
                  <DailyBabyStepsList
                    steps={healthSteps}
                    goals={goals}
                    hasGoals={hasHealthGoals}
                    onSetupGoal={() => setActiveTab('goal')}
                    emptyAction={{
                      label: t('lifeCoach.noDailyStepsCta'),
                      onClick: () => void handleGenerateSteps(),
                      loading: generatingSteps,
                      loadingLabel: t('lifeCoach.generating'),
                    }}
                    onUpdateStatus={async (id, status, detail) => {
                      await lifeCoachApi.updateDailyStepStatus(id, {status, ...detail});
                      if (detail?.reflection_text || detail?.blocker_reason) {
                        const date = todayYMD();
                        await lifeCoachApi.saveReflection({
                          date,
                          mood_score: null,
                          energy_score: null,
                          reflection_text: detail?.reflection_text || '',
                          blocker_reason: detail?.blocker_reason ?? null,
                          writing_duration_sec: detail?.writing_duration_sec ?? null,
                          reflection_word_count: detail?.reflection_word_count ?? null,
                          self_blame_language: detail?.self_blame_language ?? false,
                        });
                        await lifeCoachApi.analyzeReflection({
                          locale,
                          date,
                          reflection_text: detail?.reflection_text || '',
                          blocker_reason: detail?.blocker_reason ?? null,
                        });
                      }
                      await refresh();
                    }}
                    onRefresh={refresh}
                  />
                </div>
              </section>

              <NextActionBar
                className="hidden sm:block"
                label={quickActionLabel}
                onClick={() => void handleQuickAction()}
              />
              <MobileQuickAction
                label={quickActionLabel}
                onClick={() => void handleQuickAction()}
                loading={generatingSteps}
                loadingLabel={t('lifeCoach.generating')}
              />
            </div>
          )}

          {activeTab === 'goal' && (
            <DomainGoalTabContent
              domain="health"
              state={state}
              goals={goals}
              allRecentSteps={allRecentSteps}
              onRefresh={refresh}
              topSlot={<HealthCurrentPhase goals={goals} />}
              goalWizard={<HealthGoalWizard assessment={state} onCreated={refresh} />}
            />
          )}

          {activeTab === 'progress' && (
            <div className="grid gap-6">
              <ProgressDashboard
                domain="health"
                state={state}
                goals={goals}
                allRecentSteps={allRecentSteps}
                onRefresh={refresh}
              />
              <section className="panel-surface p-6" aria-label={t('lifeCoach.activeGoals')}>
                <h2 className="text-lg font-bold txt-strong">{t('lifeCoach.activeGoals')}</h2>
                <div className="mt-5 grid gap-4">
                  {goals.filter((goal) => goal.domain === 'health').length === 0 ? (
                    <p className="text-sm leading-7 text-[var(--muted)]">{t('lifeCoach.domainTabs.noGoalHint')}</p>
                  ) : (
                    goals
                      .filter((goal) => goal.domain === 'health')
                      .map((goal) => <GoalEditCard key={goal.id} goal={goal} onChanged={refresh} />)
                  )}
                </div>
              </section>
            </div>
          )}

          {activeTab === 'insights' && (
            <DomainInsightsTabContent
              domain="health"
              locale={locale}
              insights={insights}
              weeklyReview={weeklyReview}
              allRecentSteps={allRecentSteps}
              onRefresh={refresh}
            />
          )}
        </>
      )}
    </div>
  );
}
