'use client';

import {useEffect, useRef} from 'react';
import type {AppLocale} from '@/i18n/config';
import type {LifeDomain} from '@/lib/life-coach/types';
import {generateDomainDailySteps} from '@/lib/life-coach/generate-domain-daily-steps';

type Options = {
  domain: LifeDomain;
  enabled: boolean;
  locale: AppLocale;
  hasActiveGoal: boolean;
  domainStepCount: number;
  onDone: () => Promise<void>;
  onStart?: () => void;
  onEnd?: () => void;
};

/** Generates today's steps once when a domain has a goal but no steps yet. */
export function useAutoGenerateDomainSteps({
  domain,
  enabled,
  locale,
  hasActiveGoal,
  domainStepCount,
  onDone,
  onStart,
  onEnd,
}: Options) {
  const attemptedRef = useRef(false);

  useEffect(() => {
    if (!enabled || attemptedRef.current || !hasActiveGoal || domainStepCount > 0) return;
    attemptedRef.current = true;

    void (async () => {
      onStart?.();
      try {
        await generateDomainDailySteps(locale, domain, false);
        await onDone();
      } catch {
        /* non-fatal — user can generate manually */
      } finally {
        onEnd?.();
      }
    })();
  }, [domain, enabled, hasActiveGoal, domainStepCount, locale, onDone, onStart, onEnd]);
}
