'use client';

import {useCallback, useEffect, useMemo, useState} from 'react';
import {useLocale, useTranslations} from 'next-intl';
import type {AppLocale} from '@/i18n/config';
import {lifeCoachApi} from '@/lib/life-coach/api-client';
import {computeStreak} from '@/lib/life-coach/streak-utils';
import type {
  AiCoachingInsight,
  DailyBabyStep,
  Goal,
  LifeDomain,
  LifeDomainState,
  Milestone,
  NonHealthDomain,
} from '@/lib/life-coach/types';
import {DailyBabyStepsList} from './daily-baby-steps-list';
import {DomainGoalWizard} from './domain-goal-wizard';
import {LifeCoachAuthShell} from './life-coach-auth-shell';
import {ProgressDashboard as DomainProgressDashboard} from './shared/progress-dashboard';
import {GoalEditCard} from './shared/goal-edit-card';
import {useToast} from '@/components/feedback/toast-provider';
import {LoadingErrorPanel} from '@/components/feedback/loading-error-panel';
import {MobileQuickAction} from '@/components/feedback/mobile-quick-action';
import {AiGeneratingProgress} from './shared/ai-generating-progress';
import {StepFilterChips, type StepStatusFilter} from './step-filter-chips';
import {NextActionBar} from '@/components/feedback/next-action-bar';
import {todayYMD} from '@/lib/date-utils';
import {DomainDetailTabNav, type DomainDetailTab} from './shared/domain-detail-tabs';
import {DomainDetailCompactHeader} from './shared/domain-detail-compact-header';
import {DomainInsightsTabContent} from './shared/domain-insights-tab-content';
import {DomainGoalTabContent} from './shared/domain-goal-tab-content';
import {useAutoGenerateDomainSteps} from './shared/use-auto-generate-domain-steps';
import {generateDomainDailySteps} from '@/lib/life-coach/generate-domain-daily-steps';
import {DailyFocusCard} from './shared/daily-focus-card';
import type {DailyFocusContext} from '@/lib/daily-focus-context';

type GoalWithMilestones = Goal & {milestones?: Milestone[]};

export function DomainDetailPage({domain}: {domain: LifeDomain}) {
  return (
    <main className="section-block border-t-0">
      <div className="page-shell">
        <LifeCoachAuthShell>{() => <DomainDetailContent domain={domain} />}</LifeCoachAuthShell>
      </div>
    </main>
  );
}

function DomainDetailContent({domain}: {domain: LifeDomain}) {
  const t = useTranslations();
  const locale = useLocale() as AppLocale;
  const [loading, setLoading] = useState(true);
  const [state, setState] = useState<LifeDomainState | null>(null);
  const [goals, setGoals] = useState<GoalWithMilestones[]>([]);
  const [todaySteps, setTodaySteps] = useState<DailyBabyStep[]>([]);
  const [allRecentSteps, setAllRecentSteps] = useState<DailyBabyStep[]>([]);
  const [insights, setInsights] = useState<AiCoachingInsight[]>([]);
  const [weeklyReview, setWeeklyReview] = useState<AiCoachingInsight | null>(null);
  const [dailyFocus, setDailyFocus] = useState<DailyFocusContext | null>(null);
  const [generatingSteps, setGeneratingSteps] = useState(false);
  const [creatingMissionStep, setCreatingMissionStep] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [stepFilter, setStepFilter] = useState<StepStatusFilter>('pending');
  const [activeTab, setActiveTab] = useState<DomainDetailTab>('today');
  const [tabInitialized, setTabInitialized] = useState(false);
  const toast = useToast();

  const refresh = useCallback(async () => {
    setLoading(true);
    setLoadError(null);
    try {
      const result = await lifeCoachApi.getDomain(domain);
      setState(result.state);
      setGoals(result.goals);
      setTodaySteps(result.todaySteps);
      setAllRecentSteps(result.recentSteps.length > 0 ? result.recentSteps : result.todaySteps);
      setInsights(result.insights);
      setWeeklyReview(result.weeklyReview);
      setDailyFocus(result.dailyFocus);
    } catch {
      setLoadError(t('lifeCoach.loadError'));
    }
    setLoading(false);
  }, [domain, t]);

  useEffect(() => {
    const timeout = window.setTimeout(() => void refresh(), 0);
    return () => window.clearTimeout(timeout);
  }, [refresh]);

  const domainSteps = todaySteps.filter((step) => step.domain === domain);
  const pendingStep = domainSteps.find((step) => step.status === 'pending') ?? null;
  const hasDomainGoals = goals.some((goal) => goal.domain === domain && goal.status === 'active');
  const streak = useMemo(() => computeStreak(allRecentSteps, domain), [allRecentSteps, domain]);
  const completedToday = domainSteps.filter((s) => s.status === 'completed' || s.status === 'partial').length;

  useEffect(() => {
    if (!loading && !tabInitialized) {
      const timeout = window.setTimeout(() => {
        setActiveTab(hasDomainGoals ? 'today' : 'goal');
        setTabInitialized(true);
      }, 0);
      return () => window.clearTimeout(timeout);
    }
  }, [loading, hasDomainGoals, tabInitialized]);

  useAutoGenerateDomainSteps({
    enabled: !loading && !loadError,
    locale,
    hasActiveGoal: hasDomainGoals,
    domainStepCount: domainSteps.length,
    onStart: () => setGeneratingSteps(true),
    onEnd: () => setGeneratingSteps(false),
    onDone: refresh,
  });

  const stepFilterCounts = useMemo(
    () => ({
      pending: domainSteps.filter((s) => s.status === 'pending').length,
      completed: domainSteps.filter((s) => s.status === 'completed').length,
      skipped: domainSteps.filter((s) => s.status === 'skipped').length,
      partial: domainSteps.filter((s) => s.status === 'partial').length,
    }),
    [domainSteps]
  );
  const filteredDomainSteps = useMemo(
    () => (stepFilter === 'all' ? domainSteps : domainSteps.filter((s) => s.status === stepFilter)),
    [domainSteps, stepFilter]
  );
  const hasNonPendingSteps =
    stepFilterCounts.completed + stepFilterCounts.skipped + stepFilterCounts.partial > 0;

  async function handleGenerateSteps() {
    setGeneratingSteps(true);
    try {
      await generateDomainDailySteps(locale, domainSteps.length > 0);
      await refresh();
      toast.success(t('lifeCoach.stepsGenerated'));
      setActiveTab('today');
    } catch {
      toast.error(t('feedback.failed'));
    } finally {
      setGeneratingSteps(false);
    }
  }

  const generateLabel =
    domainSteps.length > 0 ? t('lifeCoach.regenerateTodaySteps') : t('lifeCoach.generateTodaySteps');
  const quickActionLabel = pendingStep ? t('lifeCoach.markCompleted') : generateLabel;

  async function handleQuickAction() {
    if (pendingStep) {
      try {
        await lifeCoachApi.updateDailyStepStatus(pendingStep.id, {status: 'completed'});
        await refresh();
        toast.success(t('feedback.completed'));
      } catch {
        toast.error(t('feedback.failed'));
      }
      return;
    }
    await handleGenerateSteps();
  }

  async function handleCreateMissionStep() {
    const suggested = dailyFocus?.suggestedAction;
    if (!suggested || suggested.domainId !== domain) return;

    setCreatingMissionStep(true);
    try {
      await lifeCoachApi.createDailyStep({
        goal_id: null,
        domain,
        title: suggested.title,
        description: suggested.description,
        estimated_minutes: suggested.estimatedMinutes,
        difficulty: 'easy',
        scheduled_date: todayYMD(),
        status: 'pending',
      });
      await refresh();
      toast.success(t('feedback.saved'));
    } catch {
      toast.error(t('feedback.failed'));
    } finally {
      setCreatingMissionStep(false);
    }
  }

  async function handleStepUpdate(
    id: string,
    status: 'pending' | 'completed' | 'skipped' | 'partial',
    detail?: {
      blocker_reason?: string | null;
      reflection_text?: string;
      actual_minutes?: number | null;
      writing_duration_sec?: number | null;
      reflection_word_count?: number | null;
      self_blame_language?: boolean;
    }
  ) {
    await lifeCoachApi.updateDailyStepStatus(id, {status, ...detail});
    if (detail?.reflection_text || detail?.blocker_reason) {
      const date = todayYMD();
      await lifeCoachApi.saveReflection({
        date,
        mood_score: null,
        energy_score: null,
        reflection_text: detail?.reflection_text || '',
        blocker_reason: detail?.blocker_reason ?? null,
        writing_duration_sec: detail?.writing_duration_sec ?? null,
        reflection_word_count: detail?.reflection_word_count ?? null,
        self_blame_language: detail?.self_blame_language ?? false,
      });
      await lifeCoachApi.analyzeReflection({
        locale,
        date,
        reflection_text: detail?.reflection_text || '',
        blocker_reason: detail?.blocker_reason ?? null,
      });
    }
    await refresh();
  }

  return (
    <div className="grid gap-5 pb-24 sm:pb-6">
      <DomainDetailCompactHeader
        domain={domain}
        streakDays={streak.current_streak}
        completedToday={completedToday}
        totalToday={domainSteps.length}
      />

      <DomainDetailTabNav
        value={activeTab}
        onChange={setActiveTab}
        goalSetupNeeded={!hasDomainGoals}
      />

      <LoadingErrorPanel
        loading={loading}
        error={loadError}
        onRetry={() => void refresh()}
        className="panel-surface p-6"
      />

      {!loading && !loadError && (
        <>
          {activeTab === 'today' && (
            <div className="grid gap-5">
              {!hasDomainGoals && (
                <div className="rounded-2xl border border-[var(--blue)]/20 bg-[var(--blue)]/[0.05] px-4 py-4">
                  <p className="text-sm leading-7 text-white/70">{t('lifeCoach.domainTabs.noGoalHint')}</p>
                  <button
                    type="button"
                    className="focus-ring mt-3 text-sm font-semibold text-[var(--blue)]"
                    onClick={() => setActiveTab('goal')}
                  >
                    {t('lifeCoach.domainTabs.goToGoal')} →
                  </button>
                </div>
              )}

              {generatingSteps && <AiGeneratingProgress variant="dailySteps" />}

              <DailyFocusCard
                focus={dailyFocus}
                domain={domain}
                creating={creatingMissionStep}
                onCreateMissionStep={() => void handleCreateMissionStep()}
              />

              <section
                id="domain-today-plan"
                className="panel-surface scroll-mt-24 p-5 sm:p-6"
                aria-label={t('lifeCoach.todayPlan')}
              >
                <h2 className="text-lg font-bold text-white">{t('lifeCoach.todayPlan')}</h2>
                {domainSteps.length > 0 && hasNonPendingSteps && (
                  <div className="mt-4">
                    <StepFilterChips
                      value={stepFilter}
                      onChange={setStepFilter}
                      counts={stepFilterCounts}
                    />
                  </div>
                )}
                <div className="mt-5">
                  {filteredDomainSteps.length === 0 && domainSteps.length > 0 ? (
                    <div className="grid gap-3">
                      <p className="text-sm leading-7 text-[var(--muted)]">
                        {t('lifeCoach.stepFilters.empty')}
                      </p>
                      {stepFilter !== 'all' && (
                        <button
                          type="button"
                          className="focus-ring self-start text-sm font-semibold text-[var(--blue)]"
                          onClick={() => setStepFilter('all')}
                        >
                          {t('lifeCoach.domainTabs.showAllSteps')}
                        </button>
                      )}
                    </div>
                  ) : (
                    <DailyBabyStepsList
                      steps={filteredDomainSteps}
                      goals={goals}
                      hasGoals={hasDomainGoals}
                      onSetupGoal={() => setActiveTab('goal')}
                      emptyAction={{
                        label: t('lifeCoach.noDailyStepsCta'),
                        onClick: () => void handleGenerateSteps(),
                        loading: generatingSteps,
                        loadingLabel: t('lifeCoach.generating'),
                      }}
                      onUpdateStatus={async (id, status, detail) => handleStepUpdate(id, status, detail)}
                      onRefresh={refresh}
                    />
                  )}
                </div>
              </section>

              <NextActionBar
                className="hidden sm:block"
                label={quickActionLabel}
                onClick={() => void handleQuickAction()}
              />
              <MobileQuickAction
                label={quickActionLabel}
                onClick={() => void handleQuickAction()}
                loading={generatingSteps}
                loadingLabel={t('lifeCoach.generating')}
              />
            </div>
          )}

          {activeTab === 'goal' && (
            <DomainGoalTabContent
              domain={domain}
              state={state}
              goals={goals}
              allRecentSteps={allRecentSteps}
              onRefresh={refresh}
              goalWizard={
                <DomainGoalWizard
                  domain={domain as NonHealthDomain}
                  assessment={state}
                  onCreated={refresh}
                />
              }
            />
          )}

          {activeTab === 'progress' && (
            <div className="grid gap-6">
              <DomainProgressDashboard
                domain={domain}
                state={state}
                goals={goals}
                allRecentSteps={allRecentSteps}
                onRefresh={refresh}
              />
              <section className="panel-surface p-6" aria-label={t('lifeCoach.activeGoals')}>
                <h2 className="text-lg font-bold text-white">{t('lifeCoach.activeGoals')}</h2>
                <div className="mt-5 grid gap-4">
                  {goals.filter((goal) => goal.domain === domain).length === 0 ? (
                    <p className="text-sm leading-7 text-[var(--muted)]">{t('lifeCoach.domainTabs.noGoalHint')}</p>
                  ) : (
                    goals
                      .filter((goal) => goal.domain === domain)
                      .map((goal) => <GoalEditCard key={goal.id} goal={goal} onChanged={refresh} />)
                  )}
                </div>
              </section>
            </div>
          )}

          {activeTab === 'insights' && (
            <DomainInsightsTabContent
              domain={domain}
              locale={locale}
              insights={insights}
              weeklyReview={weeklyReview}
              allRecentSteps={allRecentSteps}
              onRefresh={refresh}
            />
          )}
        </>
      )}
    </div>
  );
}
